### PR TITLE
Correct name for Las Ketchup song

### PR DESCRIPTION
**Pull request by MarauderXtreme**
I hereby declare that:

* [x] I preserved the structure of the `playlist.org` file!
* [x] I preserved the alphabetical order!
* [x] I used spaces instead of tabs for indentation!

### CODE REVIEW

**Comment by Lodifice** [comment]
I am unsure about that, as the official song name seems to be «The Ketchup Song (Aserejé)».

See https://en.wikipedia.org/wiki/The_Ketchup_Song_(Aserej%C3%A9).

**Comment by MarauderXtreme** [comment]
As I searched on discogs and Spotify the song only shows up as Aserejé. It's likely to be found by the name Ketchup Song but to make sure the automatisation works, it should be changed.

**Comment by Lodifice** [comment]
After our discussion I agree with you.

Could you please rebase this branch to the current master so that I can merge it in a clean way?

**Comment by MarauderXtreme** [comment]
Done by the last commit. Feel free.

**Pull request merged**
